<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Generated by AI.
 *
 * @package    mod_simplequiz2
 * @copyright  2024 Edunao SAS (contact@edunao.com)
 * @author     Pierre FACQ <pierre.facq@edunao.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

// Generic.
$string['pluginname'] = 'MCQ';
$string['modulename'] = 'MCQ';
$string['plugintitle'] = 'MCQ';
$string['pluginadministration'] = 'MCQ Administration';
$string['modulenameplural'] = 'MCQs';
$string['simplequiz2:addinstance'] = 'Add an MCQ activity';
$string['simplequiz2:view'] = 'View an MCQ activity';
$string['deletealluserdata'] = 'Delete all MCQ attempts';
$string['attemptsdeleted'] = 'MCQ attempts deleted';
$string['modulename_help'] = 'This activity allows you to conduct a series of multiple-choice questions.';

// Edit.
$string['converttoquiz'] = 'Convert to Quiz activity';
$string['convert_success'] = "Conversion completed successfully";
$string['cantconvertcodeerror'] = 'An error occurred while converting the module, please contact support team';

// Form.
$string['formquestiontitle'] = 'Question {$a}';
$string['formanswertitle'] = 'Answer {$a}';
$string['questiontext'] = 'Question text';
$string['iscorrectanswer'] = 'Correct answer?';
$string['addquestion'] = "Add a question";
$string['deletequestion'] = "Delete this question";
$string['notenoughanswerserror'] = 'Questions must have at least two answers.';
$string['norightanswererror'] = 'Questions must have at least one correct answer.';
$string['completionminattemptsgroup'] = 'Minimum number of attempts';
$string['completionminattempts:attempts'] = 'The student must complete or attempt the activity one or more times: {$a}';
$string['completionminattempts'] = 'The student must complete or attempt the activity one or more times: ';
$string['completionminattemptsdesc'] = 'The student must complete or attempt the activity {$a} times';

// View.
$string['question'] = 'Question';
$string['no-questions'] = "Activity under construction";
$string['check-answer'] = "Check the answer";
$string['nextquestion'] = "Next question";
$string['restart'] = "Restart";
$string['questionsuccess'] = "Correct answer";
$string['questionfail'] = "Incorrect answer";
$string['questionpartial'] = 'Partially correct answer';
$string['aria_audio'] = 'Audio: {$a->description}. Please listen to the sound.';
$string['aria_question_text'] = 'Question {$a->order}: {$a->description}';
$string['aria_answer_text'] = 'Answer: {$a->answer}';
$string['aria_restart'] = '{$a->status}: end of activity. You can restart or move to the next activity.';
$string['aria_next'] = '{$a->status}: go to the next question.';
$string['aria_video'] = 'Video: {$a->description}. Please watch the video.';
$string['aria_image'] = 'Image: {$a->description}.';
$string['aria_math'] = 'Mathematical equation.';
$string['aria_no_description'] = 'no description';
$string['session_expired_title'] = 'Session expired';
$string['session_expired_body'] = "<p>You will be redirected to the home page.<br>Please log in again to continue.</p>";
// ELEA_RQM-163: Add result page at the end of the quiz.
$string['show-results'] = 'Results';
$string['result-help'] = 'Only the highest score is kept.';
$string['result-bestscore'] = 'Best score: {$a->score}%';
$string['result-score'] = 'Score achieved: {$a->score}%';
